# Travis configuration file using the build matrix feature
# Read more under http://docs.travis-ci.com/user/build-configuration/
# THIS SCRIPT IS SUPPOSED TO BE AN EXAMPLE. MODIFY IT ACCORDING TO YOUR NEEDS!

sudo: true
language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.5"

env:
  matrix:
    - DISTRIB="conda" PYTHON_VERSION="3.5" COVERAGE="true"

addons:
  apt:
    packages:
      - git
      - python-pip

install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  # Replace dep1 dep2 ... with your dependencies
  - conda create -q -n mytravis-test-env python=$PYTHON_VERSION
  - source activate mytravis-test-env
  - pip install codecov
  - python setup.py install

script:
  # - python setup.py test
  - py.test --cov scaftravpy --cov-report term-missing
  
before_script:
  - git config --global user.email "dauerbach@ucsd.edu"
  - git config --global user.name "Dan Auerbach"

# after_success:
#   - if [[ "$COVERAGE" == "true" ]]; then bash <(curl -s https://codecov.io/bash) || echo "failed"; fi

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  - apt

